In [1]:
#1D Array
arr = [1,2,3,4,5]
print(type(arr))

<class 'list'>


In [2]:
arr.append(6)

In [3]:
arr

[1, 2, 3, 4, 5, 6]

In [4]:
#Numpy Array Formation

import numpy as np

arr = np.array(arr)
print(arr.ndim) # n Dimmentions
print(arr.shape) # Dataset Shape: row, columns
print(arr)     # print: Array

1
(6,)
[1 2 3 4 5 6]


In [5]:
# 2D array

arr1 = [[1,2,3,],[4,5,6]]
arr1 = np.array(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1)

2
(2, 3)
[[1 2 3]
 [4 5 6]]


In [6]:
#3D Array 

arr2 = [[[1,2,3],[4,5,6]]]
arr2 = np.array(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)

3
(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]


In [7]:
a = ([[1,2,3],[4,5,6,],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

c =a+b
print(c)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [8]:
a = ([[1,2,3],[4,5,6,],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

c = a*b
print(c)

[[ 10  40  90]
 [160 250 360]
 [490 640 810]]


In [9]:
a = ([[1,2,3],[4,5,6,],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

c = a/b
print(c)

[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]


Diagonal Matrix

In [12]:
a = ([[1,2,3],[4,5,6,],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3) # Diagonal Matrix

d = a+c
print(d)

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


In [13]:
a = ([[1,2,3],[4,5,6,],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3)
d = np.zeros(3)
e = np.ones(3)

z = a + e
print(z)

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
