## PRACTICING FUNCTION ARRAY 

### 1D ARRAY

In [50]:
#1D Array
arr = [1,2,3,4,5]
print(type(arr))

<class 'list'>


In [51]:
arr.append(6)

In [52]:
arr

[1, 2, 3, 4, 5, 6]

### PRACTICING NUMPY ARRAY

In [53]:
#Numpy Array Formation

import numpy as np

arr = np.array(arr)
print(arr.ndim) # n Dimmentions
print(arr.shape) # Dataset Shape: row, columns
print(arr)     # print: Array

1
(6,)
[1 2 3 4 5 6]


### PRACTICING 2D ARRAY

In [54]:
# 2D array

arr1 = [[1,2,3,],[4,5,6]]
arr1 = np.array(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1)

2
(2, 3)
[[1 2 3]
 [4 5 6]]


### PRACTICING 3D ARRAY

In [55]:
#3D Array 

arr2 = [[[1,2,3],[4,5,6]]]
arr2 = np.array(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)

3
(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]


In [56]:
a = ([[1,2,3],[4,5,6,],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

c =a+b
print(c)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [57]:
a = ([[1,2,3],[4,5,6,],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

c = a*b
print(c)

[[ 10  40  90]
 [160 250 360]
 [490 640 810]]


In [58]:
a = ([[1,2,3],[4,5,6,],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

c = a/b
print(c)

[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]


### Diagonal Matrix

In [59]:
a = ([[1,2,3],[4,5,6,],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3) # Diagonal Matrix

d = a+c
print(d)

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


In [60]:
a = ([[1,2,3],[4,5,6,],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3)
d = np.zeros(3)
e = np.ones(3)

z = a + e
print(z)

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [61]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [62]:
a*2

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
a*[2,3,4]

array([ 0.+0.j,  6.+0.j, 12.+0.j])

In [ ]:
# Changing Dtype : Datatype

a = np.array([1,2,3],dtype = 'float')
print(a)


[1. 2. 3.]


In [ ]:
a = np.array([0,2,3],dtype = 'bool')
a  

array([False,  True,  True])

In [ ]:
a = np.array([0,2,3],dtype = 'complex')
a  

array([0.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
# Arange Function
# np.arange(start,stop,step)


a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
num = np.arange(0,20)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
num.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
num.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
num.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [ ]:
num.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [ ]:
num.reshape(1,1,20)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19]]])

In [ ]:
np.linspace(1,10,8)

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [ ]:
a = np.linspace(0,20,10)
print(a.size)
a

10


array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [ ]:
num = np.arange(0,30)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
arr = num.reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
arr.max(),arr.min(),arr.mean(),arr.std()

(29, 0, 14.5, 8.65544144839919)