## PRACTICING FUNCTION ARRAY 

### 1D ARRAY

In [126]:
#1D Array
arr = [1,2,3,4,5]
print(type(arr))

<class 'list'>


In [127]:
arr.append(6)

In [128]:
arr

[1, 2, 3, 4, 5, 6]

### PRACTICING NUMPY ARRAY

In [129]:
#Numpy Array Formation

import numpy as np

arr = np.array(arr)
print(arr.ndim) # n Dimmentions
print(arr.shape) # Dataset Shape: row, columns
print(arr)     # print: Array

1
(6,)
[1 2 3 4 5 6]


### PRACTICING 2D ARRAY

In [130]:
# 2D array

arr1 = [[1,2,3,],[4,5,6]]
arr1 = np.array(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1)

2
(2, 3)
[[1 2 3]
 [4 5 6]]


### PRACTICING 3D ARRAY

In [131]:
#3D Array 

arr2 = [[[1,2,3],[4,5,6]]]
arr2 = np.array(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)

3
(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]


In [132]:
a = ([[1,2,3],[4,5,6,],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

c =a+b
print(c)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [133]:
a = ([[1,2,3],[4,5,6,],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

c = a*b
print(c)

[[ 10  40  90]
 [160 250 360]
 [490 640 810]]


In [134]:
a = ([[1,2,3],[4,5,6,],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

c = a/b
print(c)

[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]


### Diagonal Matrix

In [135]:
a = ([[1,2,3],[4,5,6,],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3) # Diagonal Matrix

d = a+c
print(d)

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


In [136]:
a = ([[1,2,3],[4,5,6,],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3)
d = np.zeros(3)
e = np.ones(3)

z = a + e
print(z)

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [137]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [138]:
# Changing Dtype : Datatype

a = np.array([1,2,3],dtype = 'float')
print(a)


[1. 2. 3.]


In [139]:
a = np.array([0,2,3],dtype = 'bool')
a  

array([False,  True,  True])

In [140]:
a = np.array([0,2,3],dtype = 'complex')
a  

array([0.+0.j, 2.+0.j, 3.+0.j])

In [141]:
# Arange Function
# np.arange(start,stop,step)


a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [142]:
num = np.arange(0,20)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [143]:
num.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [144]:
num.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [145]:
num.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [146]:
num.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [147]:
num.reshape(1,1,20)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19]]])

In [148]:
np.linspace(1,10,8)

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [149]:
a = np.linspace(0,20,10)
print(a.size)
a

10


array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [150]:
num = np.arange(0,30)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [151]:
# m : 5 :--> No.ofRows and n:6:-->No.of columns

arr = num.reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [152]:
arr.max(),arr.min(),arr.mean(),arr.std()

(29, 0, 14.5, 8.65544144839919)

In [153]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [154]:
arr.sum(axis = 1) # Row wise Addition

array([ 15,  51,  87, 123, 159])

In [155]:
arr.sum(axis = 0) # column wise Addition

array([60, 65, 70, 75, 80, 85])

In [156]:
arr[1:4,2:5]

array([[ 8,  9, 10],
       [14, 15, 16],
       [20, 21, 22]])

In [159]:
a = np.arange(50,100)
a.reshape(10,5)

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [ ]:
n = np.arange(50,100) # 1D
m = n.reshape(10,5) # 2D
print(m.ndim) # checking Dimention : 2D
m[1:3,1:3]
m

2


array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [170]:
m[1:3,1:3]

array([[56, 57],
       [61, 62]])

In [171]:
m[6:9,1:4]

array([[81, 82, 83],
       [86, 87, 88],
       [91, 92, 93]])

In [ ]:
import numpy as np

a = np.arange(101, 131, dtype="float") # in 1D Array
print(a)


[101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111. 112. 113. 114.
 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125. 126. 127. 128.
 129. 130.]


In [ ]:
b = a.reshape(5,6) # in 2D Array
print(b)

[[101. 102. 103. 104. 105. 106.]
 [107. 108. 109. 110. 111. 112.]
 [113. 114. 115. 116. 117. 118.]
 [119. 120. 121. 122. 123. 124.]
 [125. 126. 127. 128. 129. 130.]]


In [179]:
print(b.ndim)

2


In [ ]:
array = np.arange(101, 131, dtype="float").reshape(1,5,6)  # in 3D Array
array[3:,3:]

array([], shape=(0, 2, 6), dtype=float64)

In [186]:
array

array([[[101., 102., 103., 104., 105., 106.],
        [107., 108., 109., 110., 111., 112.],
        [113., 114., 115., 116., 117., 118.],
        [119., 120., 121., 122., 123., 124.],
        [125., 126., 127., 128., 129., 130.]]])